// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Context;

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("backend.Models.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Georeferencia")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INT");

                    b.Property<int>("IdMunicipio")
                        .HasColumnType("INT");

                    b.Property<int>("IdProvincia")
                        .HasColumnType("INT");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("IdDireccion");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdMunicipio");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("backend.Models.Municipio", b =>
                {
                    b.Property<int>("IdMunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdProvincia")
                        .HasColumnType("INT");

                    b.Property<string>("MunicipioNombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("IdMunicipio");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Municipios");

                    b.HasData(
                        new
                        {
                            IdMunicipio = 1,
                            IdProvincia = 5,
                            MunicipioNombre = "Distrito Nacional"
                        },
                        new
                        {
                            IdMunicipio = 2,
                            IdProvincia = 1,
                            MunicipioNombre = "Azua de Compostela"
                        },
                        new
                        {
                            IdMunicipio = 3,
                            IdProvincia = 1,
                            MunicipioNombre = "Estebanía"
                        },
                        new
                        {
                            IdMunicipio = 4,
                            IdProvincia = 1,
                            MunicipioNombre = "Guayabal"
                        },
                        new
                        {
                            IdMunicipio = 5,
                            IdProvincia = 1,
                            MunicipioNombre = "Las Charcas"
                        },
                        new
                        {
                            IdMunicipio = 6,
                            IdProvincia = 1,
                            MunicipioNombre = "Las Yayas de Viajama"
                        },
                        new
                        {
                            IdMunicipio = 7,
                            IdProvincia = 1,
                            MunicipioNombre = "Padre Las Casas"
                        },
                        new
                        {
                            IdMunicipio = 8,
                            IdProvincia = 1,
                            MunicipioNombre = "Peralta"
                        },
                        new
                        {
                            IdMunicipio = 9,
                            IdProvincia = 1,
                            MunicipioNombre = "Pueblo Viejo"
                        },
                        new
                        {
                            IdMunicipio = 10,
                            IdProvincia = 1,
                            MunicipioNombre = "Sabana Yegua"
                        },
                        new
                        {
                            IdMunicipio = 11,
                            IdProvincia = 1,
                            MunicipioNombre = "Tábara Arriba"
                        },
                        new
                        {
                            IdMunicipio = 12,
                            IdProvincia = 2,
                            MunicipioNombre = "Neiba"
                        },
                        new
                        {
                            IdMunicipio = 13,
                            IdProvincia = 2,
                            MunicipioNombre = "Galván"
                        },
                        new
                        {
                            IdMunicipio = 14,
                            IdProvincia = 2,
                            MunicipioNombre = "Los Ríos"
                        },
                        new
                        {
                            IdMunicipio = 15,
                            IdProvincia = 2,
                            MunicipioNombre = "Tamayo"
                        },
                        new
                        {
                            IdMunicipio = 16,
                            IdProvincia = 2,
                            MunicipioNombre = "Villa Jaragua"
                        },
                        new
                        {
                            IdMunicipio = 17,
                            IdProvincia = 3,
                            MunicipioNombre = "Barahona"
                        },
                        new
                        {
                            IdMunicipio = 18,
                            IdProvincia = 3,
                            MunicipioNombre = "Cabral"
                        },
                        new
                        {
                            IdMunicipio = 19,
                            IdProvincia = 3,
                            MunicipioNombre = "El Peñón"
                        },
                        new
                        {
                            IdMunicipio = 20,
                            IdProvincia = 3,
                            MunicipioNombre = "Enriquillo"
                        },
                        new
                        {
                            IdMunicipio = 21,
                            IdProvincia = 3,
                            MunicipioNombre = "Fundación"
                        },
                        new
                        {
                            IdMunicipio = 22,
                            IdProvincia = 3,
                            MunicipioNombre = "Jaquimeyes"
                        },
                        new
                        {
                            IdMunicipio = 23,
                            IdProvincia = 3,
                            MunicipioNombre = "La Ciénaga"
                        },
                        new
                        {
                            IdMunicipio = 24,
                            IdProvincia = 3,
                            MunicipioNombre = "Las Salinas"
                        },
                        new
                        {
                            IdMunicipio = 25,
                            IdProvincia = 3,
                            MunicipioNombre = "Paraíso"
                        },
                        new
                        {
                            IdMunicipio = 26,
                            IdProvincia = 3,
                            MunicipioNombre = "Polo"
                        },
                        new
                        {
                            IdMunicipio = 27,
                            IdProvincia = 3,
                            MunicipioNombre = "Vicente Noble"
                        },
                        new
                        {
                            IdMunicipio = 28,
                            IdProvincia = 4,
                            MunicipioNombre = "Dajabón"
                        },
                        new
                        {
                            IdMunicipio = 29,
                            IdProvincia = 4,
                            MunicipioNombre = "El Pino"
                        },
                        new
                        {
                            IdMunicipio = 30,
                            IdProvincia = 4,
                            MunicipioNombre = "Loma de Cabrera"
                        },
                        new
                        {
                            IdMunicipio = 31,
                            IdProvincia = 4,
                            MunicipioNombre = "Partido"
                        },
                        new
                        {
                            IdMunicipio = 32,
                            IdProvincia = 4,
                            MunicipioNombre = "Restauración"
                        },
                        new
                        {
                            IdMunicipio = 33,
                            IdProvincia = 6,
                            MunicipioNombre = "San Francisco de Macorís"
                        },
                        new
                        {
                            IdMunicipio = 34,
                            IdProvincia = 6,
                            MunicipioNombre = "Arenoso"
                        },
                        new
                        {
                            IdMunicipio = 35,
                            IdProvincia = 6,
                            MunicipioNombre = "Castillo"
                        },
                        new
                        {
                            IdMunicipio = 36,
                            IdProvincia = 6,
                            MunicipioNombre = "Eugenio María de Hostos"
                        },
                        new
                        {
                            IdMunicipio = 37,
                            IdProvincia = 6,
                            MunicipioNombre = "Las Guáranas"
                        },
                        new
                        {
                            IdMunicipio = 38,
                            IdProvincia = 6,
                            MunicipioNombre = "Pimentel"
                        },
                        new
                        {
                            IdMunicipio = 39,
                            IdProvincia = 6,
                            MunicipioNombre = "Villa Riva"
                        },
                        new
                        {
                            IdMunicipio = 40,
                            IdProvincia = 8,
                            MunicipioNombre = "El Seibo"
                        },
                        new
                        {
                            IdMunicipio = 41,
                            IdProvincia = 8,
                            MunicipioNombre = "Miches"
                        },
                        new
                        {
                            IdMunicipio = 42,
                            IdProvincia = 7,
                            MunicipioNombre = "Comendador"
                        },
                        new
                        {
                            IdMunicipio = 43,
                            IdProvincia = 7,
                            MunicipioNombre = "Bánica"
                        },
                        new
                        {
                            IdMunicipio = 44,
                            IdProvincia = 7,
                            MunicipioNombre = "El Llano"
                        },
                        new
                        {
                            IdMunicipio = 45,
                            IdProvincia = 7,
                            MunicipioNombre = "Hondo Valle"
                        },
                        new
                        {
                            IdMunicipio = 46,
                            IdProvincia = 7,
                            MunicipioNombre = "Juan Santiago"
                        },
                        new
                        {
                            IdMunicipio = 47,
                            IdProvincia = 7,
                            MunicipioNombre = "Pedro Santana"
                        },
                        new
                        {
                            IdMunicipio = 48,
                            IdProvincia = 9,
                            MunicipioNombre = "Moca"
                        },
                        new
                        {
                            IdMunicipio = 49,
                            IdProvincia = 9,
                            MunicipioNombre = "Cayetano Germosén"
                        },
                        new
                        {
                            IdMunicipio = 50,
                            IdProvincia = 9,
                            MunicipioNombre = "Gaspar Hernández"
                        },
                        new
                        {
                            IdMunicipio = 51,
                            IdProvincia = 9,
                            MunicipioNombre = "Jamao al Norte"
                        },
                        new
                        {
                            IdMunicipio = 52,
                            IdProvincia = 10,
                            MunicipioNombre = "Hato Mayor del Rey"
                        },
                        new
                        {
                            IdMunicipio = 53,
                            IdProvincia = 10,
                            MunicipioNombre = "El Valle"
                        },
                        new
                        {
                            IdMunicipio = 54,
                            IdProvincia = 10,
                            MunicipioNombre = "Sabana de la Mar"
                        },
                        new
                        {
                            IdMunicipio = 55,
                            IdProvincia = 11,
                            MunicipioNombre = "Salcedo"
                        },
                        new
                        {
                            IdMunicipio = 56,
                            IdProvincia = 11,
                            MunicipioNombre = "Tenares"
                        },
                        new
                        {
                            IdMunicipio = 57,
                            IdProvincia = 11,
                            MunicipioNombre = "Villa Tapia"
                        },
                        new
                        {
                            IdMunicipio = 58,
                            IdProvincia = 12,
                            MunicipioNombre = "Jimaní"
                        },
                        new
                        {
                            IdMunicipio = 59,
                            IdProvincia = 12,
                            MunicipioNombre = "Cristóbal"
                        },
                        new
                        {
                            IdMunicipio = 60,
                            IdProvincia = 12,
                            MunicipioNombre = "Duvergé"
                        },
                        new
                        {
                            IdMunicipio = 61,
                            IdProvincia = 12,
                            MunicipioNombre = "La Descubierta"
                        },
                        new
                        {
                            IdMunicipio = 62,
                            IdProvincia = 12,
                            MunicipioNombre = "Mella"
                        },
                        new
                        {
                            IdMunicipio = 63,
                            IdProvincia = 12,
                            MunicipioNombre = "Postrer Río"
                        },
                        new
                        {
                            IdMunicipio = 64,
                            IdProvincia = 13,
                            MunicipioNombre = "Higüey"
                        },
                        new
                        {
                            IdMunicipio = 65,
                            IdProvincia = 13,
                            MunicipioNombre = "San Rafael del Yuma"
                        },
                        new
                        {
                            IdMunicipio = 66,
                            IdProvincia = 14,
                            MunicipioNombre = "La Romana"
                        },
                        new
                        {
                            IdMunicipio = 67,
                            IdProvincia = 14,
                            MunicipioNombre = "Guaymate"
                        },
                        new
                        {
                            IdMunicipio = 68,
                            IdProvincia = 14,
                            MunicipioNombre = "Villa Hermosa"
                        },
                        new
                        {
                            IdMunicipio = 69,
                            IdProvincia = 15,
                            MunicipioNombre = "La Concepción de La Vega"
                        },
                        new
                        {
                            IdMunicipio = 70,
                            IdProvincia = 15,
                            MunicipioNombre = "Constanza"
                        },
                        new
                        {
                            IdMunicipio = 71,
                            IdProvincia = 15,
                            MunicipioNombre = "Jarabacoa"
                        },
                        new
                        {
                            IdMunicipio = 72,
                            IdProvincia = 15,
                            MunicipioNombre = "Jima Abajo"
                        },
                        new
                        {
                            IdMunicipio = 73,
                            IdProvincia = 16,
                            MunicipioNombre = "Nagua"
                        },
                        new
                        {
                            IdMunicipio = 74,
                            IdProvincia = 16,
                            MunicipioNombre = "Cabrera"
                        },
                        new
                        {
                            IdMunicipio = 75,
                            IdProvincia = 16,
                            MunicipioNombre = "El Factor"
                        },
                        new
                        {
                            IdMunicipio = 76,
                            IdProvincia = 16,
                            MunicipioNombre = "Río San Juan"
                        },
                        new
                        {
                            IdMunicipio = 77,
                            IdProvincia = 17,
                            MunicipioNombre = "Bonao"
                        },
                        new
                        {
                            IdMunicipio = 78,
                            IdProvincia = 17,
                            MunicipioNombre = "Maimón"
                        },
                        new
                        {
                            IdMunicipio = 79,
                            IdProvincia = 17,
                            MunicipioNombre = "Piedra Blanca"
                        },
                        new
                        {
                            IdMunicipio = 80,
                            IdProvincia = 18,
                            MunicipioNombre = "Montecristi"
                        },
                        new
                        {
                            IdMunicipio = 81,
                            IdProvincia = 18,
                            MunicipioNombre = "Castañuela"
                        },
                        new
                        {
                            IdMunicipio = 82,
                            IdProvincia = 18,
                            MunicipioNombre = "Guayubín"
                        },
                        new
                        {
                            IdMunicipio = 83,
                            IdProvincia = 18,
                            MunicipioNombre = "Las Matas de Santa Cruz"
                        },
                        new
                        {
                            IdMunicipio = 84,
                            IdProvincia = 18,
                            MunicipioNombre = "Pepillo Salcedo"
                        },
                        new
                        {
                            IdMunicipio = 85,
                            IdProvincia = 18,
                            MunicipioNombre = "Villa Vásquez"
                        },
                        new
                        {
                            IdMunicipio = 86,
                            IdProvincia = 19,
                            MunicipioNombre = "Monte Plata"
                        },
                        new
                        {
                            IdMunicipio = 87,
                            IdProvincia = 19,
                            MunicipioNombre = "Bayaguana"
                        },
                        new
                        {
                            IdMunicipio = 88,
                            IdProvincia = 19,
                            MunicipioNombre = "Peralvillo"
                        },
                        new
                        {
                            IdMunicipio = 89,
                            IdProvincia = 19,
                            MunicipioNombre = "Sabana Grande de Boyá"
                        },
                        new
                        {
                            IdMunicipio = 90,
                            IdProvincia = 19,
                            MunicipioNombre = "Yamasá"
                        },
                        new
                        {
                            IdMunicipio = 91,
                            IdProvincia = 20,
                            MunicipioNombre = "Pedernales"
                        },
                        new
                        {
                            IdMunicipio = 92,
                            IdProvincia = 20,
                            MunicipioNombre = "Oviedo"
                        },
                        new
                        {
                            IdMunicipio = 93,
                            IdProvincia = 21,
                            MunicipioNombre = "Baní"
                        },
                        new
                        {
                            IdMunicipio = 94,
                            IdProvincia = 21,
                            MunicipioNombre = "Nizao"
                        },
                        new
                        {
                            IdMunicipio = 95,
                            IdProvincia = 22,
                            MunicipioNombre = "Puerto Plata"
                        },
                        new
                        {
                            IdMunicipio = 96,
                            IdProvincia = 22,
                            MunicipioNombre = "Altamira"
                        },
                        new
                        {
                            IdMunicipio = 97,
                            IdProvincia = 22,
                            MunicipioNombre = "Guananico"
                        },
                        new
                        {
                            IdMunicipio = 98,
                            IdProvincia = 22,
                            MunicipioNombre = "Imbert"
                        },
                        new
                        {
                            IdMunicipio = 99,
                            IdProvincia = 22,
                            MunicipioNombre = "Los Hidalgos"
                        },
                        new
                        {
                            IdMunicipio = 100,
                            IdProvincia = 22,
                            MunicipioNombre = "Luperón"
                        },
                        new
                        {
                            IdMunicipio = 101,
                            IdProvincia = 22,
                            MunicipioNombre = "Sosúa"
                        },
                        new
                        {
                            IdMunicipio = 102,
                            IdProvincia = 22,
                            MunicipioNombre = "Villa Isabela"
                        },
                        new
                        {
                            IdMunicipio = 103,
                            IdProvincia = 22,
                            MunicipioNombre = "Villa Montellano"
                        },
                        new
                        {
                            IdMunicipio = 104,
                            IdProvincia = 23,
                            MunicipioNombre = "Samaná"
                        },
                        new
                        {
                            IdMunicipio = 105,
                            IdProvincia = 23,
                            MunicipioNombre = "Las Terrenas"
                        },
                        new
                        {
                            IdMunicipio = 106,
                            IdProvincia = 23,
                            MunicipioNombre = "Sánchez"
                        },
                        new
                        {
                            IdMunicipio = 107,
                            IdProvincia = 25,
                            MunicipioNombre = "San Cristóbal"
                        },
                        new
                        {
                            IdMunicipio = 108,
                            IdProvincia = 25,
                            MunicipioNombre = "Bajos de Haina"
                        },
                        new
                        {
                            IdMunicipio = 109,
                            IdProvincia = 25,
                            MunicipioNombre = "Cambita Garabito"
                        },
                        new
                        {
                            IdMunicipio = 110,
                            IdProvincia = 25,
                            MunicipioNombre = "Los Cacaos"
                        },
                        new
                        {
                            IdMunicipio = 111,
                            IdProvincia = 25,
                            MunicipioNombre = "Sabana Grande de Palenque"
                        },
                        new
                        {
                            IdMunicipio = 112,
                            IdProvincia = 25,
                            MunicipioNombre = "San Gregorio de Nigua"
                        },
                        new
                        {
                            IdMunicipio = 113,
                            IdProvincia = 25,
                            MunicipioNombre = "Villa Altagracia"
                        },
                        new
                        {
                            IdMunicipio = 114,
                            IdProvincia = 25,
                            MunicipioNombre = "Yaguate"
                        },
                        new
                        {
                            IdMunicipio = 115,
                            IdProvincia = 26,
                            MunicipioNombre = "San José de Ocoa"
                        },
                        new
                        {
                            IdMunicipio = 116,
                            IdProvincia = 26,
                            MunicipioNombre = "Rancho Arriba"
                        },
                        new
                        {
                            IdMunicipio = 117,
                            IdProvincia = 26,
                            MunicipioNombre = "Sabana Larga"
                        },
                        new
                        {
                            IdMunicipio = 118,
                            IdProvincia = 27,
                            MunicipioNombre = "San Juan de la Maguana"
                        },
                        new
                        {
                            IdMunicipio = 119,
                            IdProvincia = 27,
                            MunicipioNombre = "Bohechío"
                        },
                        new
                        {
                            IdMunicipio = 120,
                            IdProvincia = 27,
                            MunicipioNombre = "El Cercado"
                        },
                        new
                        {
                            IdMunicipio = 121,
                            IdProvincia = 27,
                            MunicipioNombre = "Juan de Herrera"
                        },
                        new
                        {
                            IdMunicipio = 122,
                            IdProvincia = 27,
                            MunicipioNombre = "Las Matas de Farfán"
                        },
                        new
                        {
                            IdMunicipio = 123,
                            IdProvincia = 27,
                            MunicipioNombre = "Vallejuelo"
                        },
                        new
                        {
                            IdMunicipio = 124,
                            IdProvincia = 28,
                            MunicipioNombre = "San Pedro de Macorís"
                        },
                        new
                        {
                            IdMunicipio = 125,
                            IdProvincia = 28,
                            MunicipioNombre = "Consuelo"
                        },
                        new
                        {
                            IdMunicipio = 126,
                            IdProvincia = 28,
                            MunicipioNombre = "Guayacanes"
                        },
                        new
                        {
                            IdMunicipio = 127,
                            IdProvincia = 28,
                            MunicipioNombre = "Quisqueya"
                        },
                        new
                        {
                            IdMunicipio = 128,
                            IdProvincia = 28,
                            MunicipioNombre = "Ramón Santana"
                        },
                        new
                        {
                            IdMunicipio = 129,
                            IdProvincia = 28,
                            MunicipioNombre = "San José de Los Llanos"
                        },
                        new
                        {
                            IdMunicipio = 130,
                            IdProvincia = 24,
                            MunicipioNombre = "Cotuí"
                        },
                        new
                        {
                            IdMunicipio = 131,
                            IdProvincia = 24,
                            MunicipioNombre = "Cevicos"
                        },
                        new
                        {
                            IdMunicipio = 132,
                            IdProvincia = 24,
                            MunicipioNombre = "Fantino"
                        },
                        new
                        {
                            IdMunicipio = 133,
                            IdProvincia = 24,
                            MunicipioNombre = "La Mata"
                        },
                        new
                        {
                            IdMunicipio = 134,
                            IdProvincia = 29,
                            MunicipioNombre = "Santiago"
                        },
                        new
                        {
                            IdMunicipio = 135,
                            IdProvincia = 29,
                            MunicipioNombre = "Bisonó"
                        },
                        new
                        {
                            IdMunicipio = 136,
                            IdProvincia = 29,
                            MunicipioNombre = "Jánico"
                        },
                        new
                        {
                            IdMunicipio = 137,
                            IdProvincia = 29,
                            MunicipioNombre = "Licey al Medio"
                        },
                        new
                        {
                            IdMunicipio = 138,
                            IdProvincia = 29,
                            MunicipioNombre = "Puñal"
                        },
                        new
                        {
                            IdMunicipio = 139,
                            IdProvincia = 29,
                            MunicipioNombre = "Sabana Iglesia"
                        },
                        new
                        {
                            IdMunicipio = 140,
                            IdProvincia = 29,
                            MunicipioNombre = "San José de las Matas"
                        },
                        new
                        {
                            IdMunicipio = 141,
                            IdProvincia = 29,
                            MunicipioNombre = "Tamboril"
                        },
                        new
                        {
                            IdMunicipio = 142,
                            IdProvincia = 29,
                            MunicipioNombre = "Villa González"
                        },
                        new
                        {
                            IdMunicipio = 143,
                            IdProvincia = 30,
                            MunicipioNombre = "San Ignacio de Sabaneta"
                        },
                        new
                        {
                            IdMunicipio = 144,
                            IdProvincia = 30,
                            MunicipioNombre = "Los Almácigos"
                        },
                        new
                        {
                            IdMunicipio = 145,
                            IdProvincia = 30,
                            MunicipioNombre = "Monción"
                        },
                        new
                        {
                            IdMunicipio = 146,
                            IdProvincia = 31,
                            MunicipioNombre = "Santo Domingo Este"
                        },
                        new
                        {
                            IdMunicipio = 147,
                            IdProvincia = 31,
                            MunicipioNombre = "Boca Chica"
                        },
                        new
                        {
                            IdMunicipio = 148,
                            IdProvincia = 31,
                            MunicipioNombre = "Los Alcarrizos"
                        },
                        new
                        {
                            IdMunicipio = 149,
                            IdProvincia = 31,
                            MunicipioNombre = "Pedro Brand"
                        },
                        new
                        {
                            IdMunicipio = 150,
                            IdProvincia = 31,
                            MunicipioNombre = "San Antonio de Guerra"
                        },
                        new
                        {
                            IdMunicipio = 151,
                            IdProvincia = 31,
                            MunicipioNombre = "Santo Domingo Norte"
                        },
                        new
                        {
                            IdMunicipio = 152,
                            IdProvincia = 31,
                            MunicipioNombre = "Santo Domingo Oeste"
                        },
                        new
                        {
                            IdMunicipio = 153,
                            IdProvincia = 32,
                            MunicipioNombre = "Mao"
                        },
                        new
                        {
                            IdMunicipio = 154,
                            IdProvincia = 32,
                            MunicipioNombre = "Esperanza"
                        },
                        new
                        {
                            IdMunicipio = 155,
                            IdProvincia = 32,
                            MunicipioNombre = "Laguna Salada"
                        });
                });

            modelBuilder.Entity("backend.Models.Provincia", b =>
                {
                    b.Property<int>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProvinciaNombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("IdProvincia");

                    b.ToTable("Provincias");

                    b.HasData(
                        new
                        {
                            IdProvincia = 1,
                            ProvinciaNombre = "Azua"
                        },
                        new
                        {
                            IdProvincia = 2,
                            ProvinciaNombre = "Bahoruco"
                        },
                        new
                        {
                            IdProvincia = 3,
                            ProvinciaNombre = "Barahona"
                        },
                        new
                        {
                            IdProvincia = 4,
                            ProvinciaNombre = "Dajabón"
                        },
                        new
                        {
                            IdProvincia = 5,
                            ProvinciaNombre = "Distrito Nacional"
                        },
                        new
                        {
                            IdProvincia = 6,
                            ProvinciaNombre = "Duarte"
                        },
                        new
                        {
                            IdProvincia = 7,
                            ProvinciaNombre = "Elías Piña"
                        },
                        new
                        {
                            IdProvincia = 8,
                            ProvinciaNombre = "El Seibo"
                        },
                        new
                        {
                            IdProvincia = 9,
                            ProvinciaNombre = "Espaillat"
                        },
                        new
                        {
                            IdProvincia = 10,
                            ProvinciaNombre = "Hato Mayor"
                        },
                        new
                        {
                            IdProvincia = 11,
                            ProvinciaNombre = "Hermanas Mirabal"
                        },
                        new
                        {
                            IdProvincia = 12,
                            ProvinciaNombre = "Independencia"
                        },
                        new
                        {
                            IdProvincia = 13,
                            ProvinciaNombre = "La Altagracia"
                        },
                        new
                        {
                            IdProvincia = 14,
                            ProvinciaNombre = "La Romana"
                        },
                        new
                        {
                            IdProvincia = 15,
                            ProvinciaNombre = "La Vega"
                        },
                        new
                        {
                            IdProvincia = 16,
                            ProvinciaNombre = "María Trinidad Sánchez"
                        },
                        new
                        {
                            IdProvincia = 17,
                            ProvinciaNombre = "Monseñor Nouel"
                        },
                        new
                        {
                            IdProvincia = 18,
                            ProvinciaNombre = "Monte Cristi"
                        },
                        new
                        {
                            IdProvincia = 19,
                            ProvinciaNombre = "Monte Plata"
                        },
                        new
                        {
                            IdProvincia = 20,
                            ProvinciaNombre = "Pedernales"
                        },
                        new
                        {
                            IdProvincia = 21,
                            ProvinciaNombre = "Peravia"
                        },
                        new
                        {
                            IdProvincia = 22,
                            ProvinciaNombre = "Puerto Plata"
                        },
                        new
                        {
                            IdProvincia = 23,
                            ProvinciaNombre = "Samaná"
                        },
                        new
                        {
                            IdProvincia = 24,
                            ProvinciaNombre = "Sánchez Ramírez"
                        },
                        new
                        {
                            IdProvincia = 25,
                            ProvinciaNombre = "San Cristóbal"
                        },
                        new
                        {
                            IdProvincia = 26,
                            ProvinciaNombre = "San José de Ocoa"
                        },
                        new
                        {
                            IdProvincia = 27,
                            ProvinciaNombre = "San Juan"
                        },
                        new
                        {
                            IdProvincia = 28,
                            ProvinciaNombre = "San Pedro de Macorís"
                        },
                        new
                        {
                            IdProvincia = 29,
                            ProvinciaNombre = "Santiago"
                        },
                        new
                        {
                            IdProvincia = 30,
                            ProvinciaNombre = "Santiago Rodríguez"
                        },
                        new
                        {
                            IdProvincia = 31,
                            ProvinciaNombre = "Santo Domingo"
                        },
                        new
                        {
                            IdProvincia = 32,
                            ProvinciaNombre = "Valverde"
                        });
                });

            modelBuilder.Entity("backend.Models.Direccion", b =>
                {
                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("Direcciones")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend.Models.Municipio", "Municipio")
                        .WithMany("Direcciones")
                        .HasForeignKey("IdMunicipio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend.Models.Provincia", "Provincia")
                        .WithMany("Direcciones")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Municipio");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("backend.Models.Municipio", b =>
                {
                    b.HasOne("backend.Models.Provincia", "Provincia")
                        .WithMany("Municipios")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Navigation("Direcciones");
                });

            modelBuilder.Entity("backend.Models.Municipio", b =>
                {
                    b.Navigation("Direcciones");
                });

            modelBuilder.Entity("backend.Models.Provincia", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Municipios");
                });
#pragma warning restore 612, 618
        }
    }
}
